import Head from "next/head";
import { Container, Heading, Table, Td, Thead, Tr, Spinner } from "@chakra-ui/react";
import { useProducts } from "@/features/product/useFetchProducts";
export default function Home() {
  const { data: products, isloading } = useProducts();

  const renderProducts = () => {
    return products.map((product) => {
      return (
        <Tr key={product.id}>
          <Td>{product.id}</Td>
          <Td>{product.name}</Td>
          <Td>{product.price}</Td>
          <Td>{product.description}</Td>
          <Td>{product.image}</Td>
        </Tr>
      );
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Products Page</Heading>
          <Table>
            <Thead>
              <Tr>
                <th>id</th>
                <th>name</th>
                <th>price</th>
                <th>description</th>
                <th>image</th>
              </Tr>
            </Thead>
            <tbody>
              {renderProducts()}
              {isloading && <Spinner />}
            </tbody>
          </Table>
        </Container>
      </main>
    </>
  );
}
